name: Base News Bot

on:
  schedule:
    - cron: "0 5,17 * * *"   # runs every day at 05:00 and 17:00 UTC
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Download dependencies
        run: go mod tidy

      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL: ${{ secrets.TELEGRAM_CHANNEL }}
          WINDOW_HOURS: "168"
          MAX_POSTS: "10"
        run: go run main.go
